In [34]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder  

from sklearn.model_selection import train_test_split
import pickle
import datetime

In [8]:
data=pd.read_csv("diabetes.csv")
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [11]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [18]:
#independent and dependent features
X=data.drop('Outcome',axis=1)
Y=data['Outcome']

In [20]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [21]:
#Split the data into train and test
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [24]:
#Scale the features
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [26]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [27]:
import tensorflow as tf

WARNING:tensorflow:From c:\Users\AdithyaP\OneDrive\Documents\DiabetesPrediction\venv1\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [28]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
#Building the Artificial Neural Network
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],),),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid'),
])

In [31]:
#Compiling the Model
model.compile(optimizer='Adam',loss="binary_crossentropy",metrics=['accuracy'])

WARNING:tensorflow:From c:\Users\AdithyaP\OneDrive\Documents\DiabetesPrediction\venv1\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [36]:
#Set up tensorboard
log_dir='logs/fit/'+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tf_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [47]:
earlystoppingcallback=EarlyStopping(monitor="val_loss",patience=5,restore_best_weights=True)

In [48]:
#Train the Model
history=model.fit(X_train_scaled,Y_train,validation_data=(X_test_scaled,Y_test),epochs=100,
                  callbacks=[tf_callback,earlystoppingcallback],
                  )

Epoch 1/100
20/20 [==============================] - 1s 37ms/step - loss: 0.4534 - accuracy: 0.7834 - val_loss: 0.4968 - val_accuracy: 0.7792
Epoch 2/100
20/20 [==============================] - 0s 22ms/step - loss: 0.4466 - accuracy: 0.7932 - val_loss: 0.4979 - val_accuracy: 0.7662
Epoch 3/100
20/20 [==============================] - 0s 26ms/step - loss: 0.4406 - accuracy: 0.7932 - val_loss: 0.5000 - val_accuracy: 0.7727
Epoch 4/100
20/20 [==============================] - 0s 17ms/step - loss: 0.4360 - accuracy: 0.7915 - val_loss: 0.5061 - val_accuracy: 0.7662
Epoch 5/100
20/20 [==============================] - 0s 21ms/step - loss: 0.4327 - accuracy: 0.7899 - val_loss: 0.5094 - val_accuracy: 0.7597
Epoch 6/100
20/20 [==============================] - 0s 17ms/step - loss: 0.4283 - accuracy: 0.7948 - val_loss: 0.5101 - val_accuracy: 0.7662

In [49]:
model.save("model.h5")

c:\Users\AdithyaP\OneDrive\Documents\DiabetesPrediction\venv1\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [50]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [51]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6009 (pid 1712), started 0:11:44 ago. (Use '!kill 1712' to kill it.)